/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOn: typeof import('./src/components/layout/AddOn.vue')['default']
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    FoodMenu: typeof import('./src/components/layout/AddOn/FoodMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageNoticeMain: typeof import('./src/components/page/Board/Notice/ImageNoticeMain.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    LunchMenu: typeof import('./src/components/layout/AddOnPack/LunchMenu.vue')['default']
    MusicBox: typeof import('./src/components/layout/AddOnPack/MusicBox.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeMainCopy: typeof import('./src/components/page/Board/Notice/NoticeMainCopy.vue')['default']
    NoticeModal: typeof import('./src/components/page/Board/Notice/NoticeModal.vue')['default']
    NoticeModalCopy: typeof import('./src/components/page/Board/Notice/NoticeModalCopy.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    NoticeSearchCopy: typeof import('./src/components/page/Board/Notice/NoticeSearchCopy.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnowSkin: typeof import('./src/components/layout/AddOnPack/SnowSkin.vue')['default']
  }
}
