/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOn: typeof import('./src/components/layout/AddOn.vue')['default']
    ApprovalMain: typeof import('./src/components/page/Approval/ApprovalMain.vue')['default']
    ApprovalMainTanstack: typeof import('./src/components/page/Approval/ApprovalMainTanstack.vue')['default']
    ApprovalSearch: typeof import('./src/components/page/Approval/ApprovalSearch.vue')['default']
    CompanyWrite: typeof import('./src/components/page/Company/CompanyWrite.vue')['default']
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HirePostMain: typeof import('./src/components/page/HirePost/HirePostMain.vue')['default']
    HirePostSearch: typeof import('./src/components/page/HirePost/HirePostSearch.vue')['default']
    ImageNoticeMain: typeof import('./src/components/page/Board/Notice/ImageNoticeMain.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    LunchMenu: typeof import('./src/components/layout/AddOnPack/LunchMenu.vue')['default']
    MusicBox: typeof import('./src/components/layout/AddOnPack/MusicBox.vue')['default']
    NoticeDetail: typeof import('./src/components/page/Board/Notice/NoticeDetail.vue')['default']
    NoticeDetailTanstack: typeof import('./src/components/page/Board/Notice/NoticeDetailTanstack.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeMainTanstack: typeof import('./src/components/page/Board/Notice/NoticeMainTanstack.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    NoticeSearchTanstack: typeof import('./src/components/page/Board/Notice/NoticeSearchTanstack.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnowSkin: typeof import('./src/components/layout/AddOnPack/SnowSkin.vue')['default']
  }
}
